### ISSUE TITLE
limiting statsmodels to version 0.8.0 causes problems

### ISSUE THREAD

**Issue by oshev** [scikit-learn-contrib/categorical-encoding#123]
Hi, why do you need to limit the dependency statsmodels to the version 0.8.0? This version can't be easily installed with the latest Cython, it throws exceptions. However, the latest version of statsmodels 0.9.0 installs easily. Can statsmodels be updated to 0.9.0 in requirements.txt?

```
    Exception: Cython-generated file 'statsmodels/tsa/kalmanf/kalman_loglike.c' not found.
            Cython is required to compile statsmodels from a development branch.
            Please install Cython or download a source release of statsmodels.
```

After installing Cython with `brew install cython`, I still have the same problem.

**Comment by janmotl** [comment]
It is because of https://github.com/scikit-learn-contrib/categorical-encoding/issues/69.

Nevertheless:
1. all tests in categorical-encoding library pass with statsmodels 0.9.0
2. pip on macOS 10.13 does not have any problem with 0.9.0
3. conda on TravisCI does not have any problem with 0.9.0

Hence, I removed the cap.

**Comment by oshev** [comment]
Yes, 0.9.0 works fine with both pip and conda as you pointed out. Thank you so much for the fix!
