### ISSUE TITLE
BaseNEncoder: inverse_transform is incompatible with Numpy inputs

### ISSUE THREAD

**Issue by Tallic** [scikit-learn-contrib/categorical-encoding#196]
Listing 
```
import category_encoders
import numpy as np

arr = np.array([[f"cat{i}"] for i in np.random.randint(0, 10, 100)])

enc = category_encoders.BaseNEncoder(return_df=False)
enc.fit(arr)

arr_encoded = enc.transform(arr)
arr_decoded = enc.inverse_transform(arr_encoded)

assert np.array_equal(arr, arr_decoded)
```

will lead to a `TypeError: 'deep' is an invalid keyword argument for this function` exception contradicting the [API documentation](http://contrib.scikit-learn.org/categorical-encoding/basen.html#category_encoders.basen.BaseNEncoder.inverse_transform) that it can handle Numpy arrays.
Note: Array-like is anything that can be converted to a Numpy array.

**Problem** is *line 261* in basen.py that uses the Pandas only argument `deep` that does not exist on the Numpy side. A second potential problem location might be *line 320* using the same argument.

**Solution A** remove the `deep` arguments on the copy statements as a shallow copy should suffice -- you are changing the array by mapping the values to newly created once.
**Solution B** make the copy conditional on the input type -- with `deep` for data frames and without for Numpy arrays.

Package | Version | Source
---- | ---- | ---- |
category_encoder | 2.0.0 | conda-forge
numpy | 1.16.3 | conda-forge
pandas | 0.23.4 | conda-forge

**Comment by janmotl** [comment]
Thank you for the bug report. The described breaking point is already fixed in the master branch. Nevertheless, `inverse_transform()` still fails on Numpy ndarray.

Facts:
1. The encoders support encoding of multiple features at once. 
2.`inverse_transform()` must know which columns in the encoded data belong together (i.e.: which columns in the encoded data make a single categorical feature in the input data).

The issue:
Currently, the encoder remembers the grouping based on the column names. This is nice because `inverse_transform()` works on a DataFrame, even if you permute and/or add new columns. But Numpy ndarray does not store column names... 

The proposed solution:
Remember not only the column names, but also indexes. On DataFrames, column names would be used (to preserve compatibility with the current implementation). Otherwise, indexes would be used.

What do you think?

**Comment by Tallic** [comment]
Sounds reasonable.

Maybe as **context**, we use a separate feature description mechanism to handle the madness of changing features across libraries their models and transformations.
A FeatureDescriptor memorizes input and output features by id (column names) and position (indexes). The order of features is fixed and computed by the descriptor.
It is more restrictive than your name based approach, as you can only apply data frames that match the descriptor.
However, it makes the operations themselves more robust since you can fail fast if data does not match the description.

From this point of view, the whole Pandas support in the category_encoders is helpful, but the problem of feature management might outgrow it very quickly in a production setting. A strong Numpy base (using fixed index dimensions) would be preferable with an additional pandas layer above (maybe wrapper transformers).

**Comment by Tallic** [comment]
A **workaround** for this issues is given by the listing below
```
import category_encoders
import numpy as np
import pandas as pd

arr = np.array([[f"cat{i}"] for i in np.random.randint(0, 10, 100)])

enc = category_encoders.BaseNEncoder(return_df=False)
enc.fit(arr)

arr_encoded = enc.transform(arr)
arr_decoded = enc.inverse_transform(pd.DataFrame(arr_encoded, columns=enc.get_feature_names()))

assert np.array_equal(arr, arr_decoded)
```

**Comment by janmotl** [comment]
Nice. Fixed in https://github.com/scikit-learn-contrib/categorical-encoding/commit/11d52270c1e37b5945956fb773184a0fce1384e1
