### ISSUE TITLE
Adding variable names to enconding

### ISSUE THREAD

**Issue by davidsbatista** [scikit-learn-contrib/categorical-encoding#21]
Is it possibly, for instance, with one-hot encoding to add to the variable name, the variable value? e.g.: with the variable `gender` having the following values: `unknown`, `male`, `female`

encoded as three variables with names:
`gender_unknown`	`gender_male`	`gender_female`

instead of:
`gender_0`	`gender_1`	`gender_2`

**Comment by wdm0006** [comment]
I've thought about this a good bit, it's tricky for the case where the values aren't nice<sup>TM</sup>.  So if the labels have odd characters, spaces, are extremely long, etc, then they may not make great column names. 

So that was the original rationale behind using the index instead. 

What we could, and probably should, do instead though, is expose `self.ordinal_encoder.mapping` as a property in encoders such as one-hot, so the user can after-the-fact access the mapping of 0-unknown, 1-male, 2-female in your example. 

For your usecase would that be suitable? We could also make a helper function to swap the index based headers out for labels, but I think still leaving the indices there by default makes sense.

**Comment by davidsbatista** [comment]
just exposing the mapping would be enough

**Comment by wdm0006** [comment]
Ok, are you interested in working on a PR for this?

**Comment by davidsbatista** [comment]
Yes, I can start working on it. Although it might take some time, have too much on my plate right.

**Comment by wdm0006** [comment]
Awesome, let me know if you run into any trouble.
