### ISSUE TITLE
OrdinalEncoder mapping

### ISSUE THREAD

**Issue by santosh-b** [scikit-learn-contrib/categorical-encoding#228]
Why does the mapping parameter in the OrdinalEncoder require me to specify a column? I want to be able use a mapping dictionary to OrdinalEncode multiple columns at once, but because I'm only able to specify a column, and only 1 column, I'm not able to do this.

This is what i'm talking about:
```
**ordinal.py**
mapping: list of dict
        a mapping of class to label to use for the encoding, optional.
        the dict contains the keys 'col' and 'mapping'.
        the value of 'col' should be the feature name.
        the value of 'mapping' should be a dictionary of 'original_label' to 'encoded_label'.
        example mapping: [{'col': 'col1', 'mapping': {None: 0, 'a': 1, 'b': 2}}]
```
I don't want to have to specify a single feature name, but it looks like if I use the mapping parameter then I'm forced to

**Comment by janmotl** [comment]
There are two things.
> Why does the mapping parameter in the OrdinalEncoder require me to specify a column?

Internally, categorical encoders use indexing based on column names and not based on position index. Historically, it was making sense, because some encoders encode a single column into multiple columns. And columns names were helping to keep track of what's going on.

> I want to be able use a mapping dictionary to OrdinalEncode multiple columns at once

It is possible to provide mapping for multiple columns at once:
```python
import category_encoders as encoders
enc = encoders.OrdinalEncoder(mapping = [{'col': 'unique_str', 'mapping': {None: 0, '1': 1, '2': 2, '3': 3}},
                                         {'col': 'categorical', 'mapping': {None: 0, 'A': 1, 'B': 2, 'C': 3, 'D': 3}}
                                         ])
result = enc.fit_transform(X)
```
If you are passing a numpy array, then the column names are integers starting with 0 from the left. 

Currently, the syntax for mapping is defined by the internals. If you would prefer different syntax, let me know.

**Comment by santosh-b** [comment]
Ah, that makes total sense. The docs were a bit hard to read regarding being able to use multiple dicts to map to multiple columns, but that's probably just me. Thanks
