### ISSUE TITLE
Make use of multiprocessing module?

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [scikit-learn-contrib/categorical-encoding#37]
Hello,

Thanks for your work on this. Is there any way we can make use of the multiprocessing module here? I have this snippet,

```
# Specify the columns to encode then fit and transform
encoder = ce.binary.BinaryEncoder(cols=[.......],return_df=True)
encoder.fit(inputdatav1, verbose=1)

inputdatav2 = encoder.transform(inputdatav1)
```

I am trying to encode 9 categorical columns, I know 7 of them has less than 100 levels in it, however two columns are big, one has 40702 and another one has 48112 unique values respectively. My encoding is running for past 7 hours, is there a way to speed up the process?

**Comment by wdm0006** [comment]
40,000 is quite a few levels.  There are for sure some performance optimizations we could/should make in there. Some things are calculated in the loop that really can just be done once, we could probably be smarter about the execution itself as well. 

The simplest place for parallelization with something like joblib or multiprocessing would be do process multiple columns at the same time, which I don't think would help you all that much here. 

I'd guess the most time is spent in the map here: https://github.com/scikit-learn-contrib/categorical-encoding/blob/master/category_encoders/binary.py#L195

But haven't profiled it or anything.

**Comment by usingamgad** [comment]
@wdm0006 Why this issue is closed? I'm facing a similar issue. The Binary encoders is quite slow, is there anyway to make it faster?

**Comment by wdm0006** [comment]
It was closed just because it was open ended. We, in general, do want to increase throughput and scalability for all of the encoders and there are probably ways we can do that (and since this issue we have made some improvements in other encoders). 

If anyone is interested in working on computational performance benchmarking and improvements, that'd be great and I'd be happy to help, but otherwise it'll probably be a few weeks until I'll have suitable time to sit down and work through it myself.
