### ISSUE TITLE
Create inverse_transform functionality

### ISSUE THREAD

**Issue by edwardcjohnson** [scikit-learn-contrib/categorical-encoding#44]
Could the inverse_transform functionality that exists in sklearn encoders be introduced?
This would allow a user to obtain the original levels prior to encoding.

See the examples section in:
http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

**Comment by wdm0006** [comment]
For some of the encoders, notable ordinal, onehot, basen, and binary: yes for sure, we can and should do that. For some like hashing, not really.

Are you interested in helping to work on a PR for maybe ordinal encoding to start with?

**Comment by wenwu313** [comment]
@wdm0006 hey man, I want to try this fucking issue

**Comment by wdm0006** [comment]
Hm. That's a good question. The clearest thing would be to raise a ValueError or something like that in those cases and tell the user they can't use inverse transform if they are using drop_invariant or impute_missing. 

Otherwise you'd have to keep some state in the class to maintain an ability to repopulate those, which would be a pretty heavy addition.
