### ISSUE TITLE
What should 'None' be converted as ?

### ISSUE THREAD

**Issue by wenwu313** [scikit-learn-contrib/categorical-encoding#52]
```
>>> import pandas as pd
>>> import category_encoders as ce
>>> df = pd.DataFrame({'col1':[None, 'a', 'b']})
>>> print df
   col1
0  None
1     a
2     b

>>> enc = ce.OrdinalEncoder(verbose=1)
>>> enc.fit(df)
>>> print enc.category_mapping
[{'col': 'col1', 'mapping': [(None, 0), ('a', 1), ('b', 2)]}]

>>> print enc.transform(df)
   col1
0    -1
1     1
2     2
```
As above, 'None' is converted as -1, but in the mapping , 'None' is mapped as 0. What should 'None' be converted as? why not converted as 0?
And I find 
```
(line 251 in ordinal.py)
X.loc[X[switch.get('col')] == category[0], str(switch.get('col')) + '_tmp'] = str(category[1])   

for example :
>>> print None == None
True
>>> X = pd.DataFrame({'col1':[None, 'a', 'b']})
   col1
0  None
1     a
2     b
>>> print X['col1'] == None
0    False
1    False
2    False
```
Is there any problem? 

For 'None' , there is difference between numpy and pandas , pandas always treat 'None' as nan, but numpy treat 'None' as NoneType. Is it necessay to modify as follows ?
```
X.loc[X[switch.get('col')].values == category[0], str(switch.get('col')) + '_tmp'] = str(category[1])   

Add .values turn Series to array!
```

**Comment by wdm0006** [comment]
Hm, yeah that looks like a bug. -1 is for unknown categories (so a category showing up in transform that wasnt seen in fit), which clearly, it shouldn't have been.  I think you're correct that root cause here is the None vs. nan mixup. 

Not sure the easiest way to resolve this, since we cast to pandas always, we can treat Nonetypes in mappings special maybe? I'll have to think on that some. 

Great catch, btw.

**Comment by wdm0006** [comment]
see #56
