### ISSUE TITLE
handle_unknown

### ISSUE THREAD

**Issue by zimka** [scikit-learn-contrib/categorical-encoding#57]
Hello!
I have faced smth that looks like a bug for me.
![screenshot-enc](https://user-images.githubusercontent.com/4560910/35469534-6fb07356-0347-11e8-8e7b-855c29a9f833.png)
[traceback.txt](https://github.com/scikit-learn-contrib/categorical-encoding/files/1669832/traceback.txt)
Same behavior for other encoders that have this check:
https://github.com/scikit-learn-contrib/categorical-encoding/blob/master/category_encoders/ordinal.py#L260
I am not sure, but I haven't managed to find where key 'D' is set in package, so may be this check is bogus

**Comment by wdm0006** [comment]
Do you see the same error in v1.2.6?

**Comment by gavin-s-smith** [comment]
Yes, I can confirm this error (same code) v1.2.6.

This looks like a bug. The statement block in question is:

if X[~X['D'].isin([str(x[1]) for x in switch.get('mapping')])].shape[0] > 0:
                            raise ValueError('Unexpected categories found in %s' % (switch.get('col'),))

At this point the code is looping over each column and converting the string representation to the ordinal one - if there is no match in the previously learnt mapping then it is mapped to NaN.

Then we look to impute and/or check which, assuming we've picked this option, is when the above block is run.

The above check is a generic though, and just checking if the (newly mapped) ordinal encoding values in the column X['D'] are valid. Of course since we are looping over columns in X (and in any case have an arbitrary DataFrame) the column 'D' almost certainly doesn't exist and this is a bug. The current column is given by switch.get('col'). As such the corrected code is:

if X[~X[switch.get('col')].isin([str(x[1]) for x in switch.get('mapping')])].shape[0] > 0:
                            raise ValueError('Unexpected categories found in %s' % (switch.get('col'),))

**Comment by wdm0006** [comment]
Good catch! Would you be interested in putting together a PR with this bug fix?
